<a href="https://colab.research.google.com/github/bsheese/cs377/blob/main/16_ml_intro/16_5_Pandas_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas Dataframes

## Introduction

Think of a Pandas DataFrame as a digital spreadsheet. It is a two-dimensional container where data is neatly arranged into rows and columns. If a Series is a single column of data, a DataFrame is a collection of those columns all tied together by a shared index. While it may take a little practice to master the full power of the DataFrame, the transition is easy: if you understand Series, you already know the fundamentals of how DataFrames work.

The shared index is going to allow us to examine, organize, manipulate lots of data very efficiently. The good news is that if you've completed the previous section on Series, you'll find most of what we are going to do with Dataframes to be similar, if not identical.

We will explore just a few things you can do with Dataframes in this course. If you want to see what else is available, [the Pandas documentation covers the wide variety of methods we won't touch on](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html).

In [72]:
# make sure you always do the import that makes pandas available
import pandas as pd

## Creating and Copying Dataframes

### Creating Dataframes

To create a new Dataframe, we can use the `pd.DataFrame` method. Empty Dataframes can be constructed by using the `.DataFrame()` method without any arguments. Note that the 'D' and the 'F' in `.DataFrame()` are capitalized.

In [73]:
# constructing an empty Dataframe
my_df = pd.DataFrame()
type(my_df) # checking the datatype of the result

pandas.core.frame.DataFrame

### Creating a Dataframe from a CSV

We usually won't start with an empty Dataframe.  Instead, we will create it by reading a .csv file.
To do so, we use the `pd.read_csv()` method with the file name as an argument.

By convention, dataframes are often assigned to the variable `df`. I'd like you to stick with this convention, if you are working with one dataframe at a time.

In [74]:
# read the csv file and assign the result to df
url = 'https://raw.githubusercontent.com/bsheese/CSDS125ExampleData/master/data_albums_sales_wikipedia.csv'
df = pd.read_csv(url)

#check the result
df.head()

,artist,album,year,genre,cert_sales,claim_sales
0,Michael Jackson,Thriller,1982,"Pop, post-disco, funk, rock",47.3,66
1,AC/DC,Back in Black,1980,Hard rock,29.4,50
2,Meat Loaf,Bat Out of Hell,1977,"Hard rock, glam rock, progressive rock",21.7,50
3,Pink Floyd,The Dark Side of the Moon,1973,Progressive rock,24.4,45
4,Whitney Houston / Various artists,The Bodyguard,1992,"R&B, soul, pop, soundtrack",28.4,45

The Dataframe we have constructed is built out of data from the wikipedia page on [best-selling music albums](https://en.wikipedia.org/wiki/List_of_best-selling_albums).

### Copying DataFrames
Making a copy of a DataFrame is exactly like making a copy of a Series. If you want to duplicate a DataFrame, you need to be careful not to accidentally make an alias that refers to the same DataFrame object instead of making an entirely new object. To explicitly make a copy of a DataFrame you can use the `.copy()` method, just as you would with a list or Series.

In [75]:
# the code below does NOT make a copy of the Dataframe, it only makes an alias

df_alias = df # this just created a second name for the same object

df_alias is df # this checks to see if they are the same object

True

In [76]:
# the code below makes a copy of the dataframe

df_copy = df.copy() # notice we've added the copy method here

df_copy is df # this checks to see if they are the same object

False

## Examining the Dataframe

### .info()
We can use the Dataframe method, `.info()`, to get a brief summary of the Dataframe. This is a handy method that contains quite a bit of information that will eventually come in useful. For now, just pay attention to the number of entries which indicates the number of rows in the dataframe and the specific column names.

In [77]:
# view information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   artist       33 non-null     object
 1   album        33 non-null     object
 2   year         33 non-null     int64
 3   genre        33 non-null     object
 4   cert_sales   33 non-null     float64
 5   claim_sales  33 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 1.7+ KB

### .head() and .tail()
`.head()` and `.tail()` both work with Dataframes, but now show the first and last rows of all columns in the dataframe.

In [78]:
# view the first three rows
df.head(3)

,artist,album,year,genre,cert_sales,claim_sales
0,Michael Jackson,Thriller,1982,"Pop, post-disco, funk, rock",47.3,66
1,AC/DC,Back in Black,1980,Hard rock,29.4,50
2,Meat Loaf,Bat Out of Hell,1977,"Hard rock, glam rock, progressive rock",21.7,50

In [79]:
# view the last three rows
df.tail(3)

,artist,album,year,genre,cert_sales,claim_sales
30,Santana,Supernatural,1999,Latin rock,20.5,30
31,Guns N' Roses,Appetite for Destruction,1987,Hard rock,21.9,30
32,Elton John,Goodbye Yellow Brick Road,1973,"rock, pop rock glam rock",8.5,30

### `.value_counts()`

The `.info()` summary told us `genre` is an `object` (text) column, but not *what* is in it. When a column holds categories rather than numbers, we usually want to know how many rows fall into each category. `.value_counts()` tallies the unique values in a single column and returns them sorted from most common to least.

This is one of the most-used tools in the whole course. When we reach classification, it is how we check the **class balance** — how many examples we have of each category we are trying to predict.

In [ ]:
# count how many albums fall into each genre
df['genre'].value_counts()

### Examining index and column attributes
As with a Series, we can examine the index of a Dataframe using dot notation. In this case, no data was specified as an index, so the index is a range object that produces integers for each row.

In [80]:
# view the dataframe's index
df.index

RangeIndex(start=0, stop=33, step=1)

The columns of a Dataframe can also be examined using dot notation to access the column attribute.

In [81]:
# view the dataframe's columns
df.columns

Index(['artist', 'album', 'year', 'genre', 'cert_sales', 'claim_sales'], dtype='object')

## Working with the Index and Columns

### Setting and Resetting the Index
You can transform any column into the DataFrame's index using the .set_index() method. This is particularly useful when your analysis revolves around a specific field, as it makes many operations more intuitive. For those working with large amounts of data, setting and sorting the index provides a substantial speed boost for many common tasks.

In [82]:
# the current index is just a range object because no index was specified
df.head(3)

,artist,album,year,genre,cert_sales,claim_sales
0,Michael Jackson,Thriller,1982,"Pop, post-disco, funk, rock",47.3,66
1,AC/DC,Back in Black,1980,Hard rock,29.4,50
2,Meat Loaf,Bat Out of Hell,1977,"Hard rock, glam rock, progressive rock",21.7,50

In [83]:
# uses the label of the artist series to set the index
df = df.set_index('artist')

# the artist series now serves as the shared index for the Dataframe
df.head(3)

,album,year,genre,cert_sales,claim_sales
artist,,,,,
Michael Jackson,Thriller,1982,"Pop, post-disco, funk, rock",47.3,66
AC/DC,Back in Black,1980,Hard rock,29.4,50
Meat Loaf,Bat Out of Hell,1977,"Hard rock, glam rock, progressive rock",21.7,50

If we want to move a series back out of the index, we can do so by using `reset_index()`.

In [84]:
# moves whatever series is in the index back out into the regular columns
df = df.reset_index()

# with no specified index, the range object has been applied as the index
df.head(3)

,artist,album,year,genre,cert_sales,claim_sales
0,Michael Jackson,Thriller,1982,"Pop, post-disco, funk, rock",47.3,66
1,AC/DC,Back in Black,1980,Hard rock,29.4,50
2,Meat Loaf,Bat Out of Hell,1977,"Hard rock, glam rock, progressive rock",21.7,50

In [85]:
# setting year as the index
df = df.set_index('year')

# sort by index (year)
df = df.sort_index()

#check the result
df.head()

,artist,album,genre,cert_sales,claim_sales
year,,,,,
1967,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32
1969,The Beatles,Abbey Road,Rock,14.4,30
1971,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37
1973,Pink Floyd,The Dark Side of the Moon,Progressive rock,24.4,45
1973,Elton John,Goodbye Yellow Brick Road,"rock, pop rock glam rock",8.5,30

### Updating Index Labels and Column Labels

Just like a Series, the Dataframe index object and the Dataframe column object are not mutable. However, we can modify either a list or a series and assign it to the index or columns. Note: The list or series you are using to replace the index of columns must be the same length as the index or columns in the existing dataframe.

In [86]:
# an example of updating the index labels

# copy the index into a list
year_list = df.index.to_list()

# create a list of decades from year_list
decade_list = [(year // 10) * 10 for year in year_list]

# convert the list into a series, and set the series name
decade_series = pd.Series(data=decade_list, name='decade')

# kick year out of the index, so we don't overwrite it
df = df.reset_index()

# assign decade_series to the index
df.index = decade_series

# check the result
df.head()

,year,artist,album,genre,cert_sales,claim_sales
decade,,,,,,
1960,1967,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32
1960,1969,The Beatles,Abbey Road,Rock,14.4,30
1970,1971,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37
1970,1973,Pink Floyd,The Dark Side of the Moon,Progressive rock,24.4,45
1970,1973,Elton John,Goodbye Yellow Brick Road,"rock, pop rock glam rock",8.5,30

In [87]:
# an example of updating the column index
df.columns = df.columns.str.capitalize()

# check the result
df.head()

,Year,Artist,Album,Genre,Cert_sales,Claim_sales
decade,,,,,,
1960,1967,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32
1960,1969,The Beatles,Abbey Road,Rock,14.4,30
1970,1971,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37
1970,1973,Pink Floyd,The Dark Side of the Moon,Progressive rock,24.4,45
1970,1973,Elton John,Goodbye Yellow Brick Road,"rock, pop rock glam rock",8.5,30

Because 'decade' is the name of the index, it was not capitalized when we reassigned the column names. A quick way to address this with the code we've already written, would be to reset the index to move decade into the columns before we do the column labels update.

### Switching Back
That demonstrated two useful techniques: updating index labels and modifying column names. For the rest of this notebook, we'll work with lowercase column names and year as the index, so let's switch back.

In [88]:
# reassign column labels to a non-capitalized form
df.columns = df.columns.str.lower()

# move decade out of the index and into the columns
df = df.reset_index()

# move year into the index
df = df.set_index('year')

# check the result
df.head(3)

,decade,artist,album,genre,cert_sales,claim_sales
year,,,,,,
1967,1960,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32
1969,1960,The Beatles,Abbey Road,Rock,14.4,30
1971,1970,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37

Now that we can construct and examine a Dataframe, let's learn how to select specific subsets of data from it.

## Dataframes: Selecting Data

### Selecting Data Using the Index and Columns
Up to this point, we have only been indexing and slicing Series based on the index. We will continue to do this with Dataframes, and it will work in much the same way, but, since we now have both columns and rows we can now index and slice both rows and columns at the same time.

### Selection by Label Using `.loc`
We are going to use `.loc[]` with Dataframes in much the same way we used it with Series. However, now we are going to specify both the row labels and the column labels that we want.

We can start by asking for a single index label, the integer `1992` and a single column label `'artist'`. Since there is only one value for that year, we get back a single value. Notice that the index label and the column name are separated by a comma.

In [89]:
# single index label and a single column label
df.loc[1971, 'artist']

'Led Zeppelin'

In [90]:
# an index slice followed by a column slice
df.loc[1977:1979, 'artist':'album']

,artist,album
year,,
1977,Fleetwood Mac,Rumours
1977,Bee Gees / Various artists,Saturday Night Fever
1977,Meat Loaf,Bat Out of Hell
1978,Various artists,Grease: The Original Soundtrack from the Motio...
1979,Pink Floyd,The Wall

In [91]:
# a single index label, followed by a column slice
df.loc[1987, 'artist':'album']

               artist                     album
year
1987    Guns N' Roses  Appetite for Destruction
1987  Various artists             Dirty Dancing
1987  Michael Jackson                       Bad

In [92]:
# an index slice (with no stop value), followed by a single column label
df.loc[2000:,'artist']

year
2000    The Beatles
2011          Adele
Name: artist, dtype: object

As an alternative to slicing we can pass lists with specific index labels or column names.

In [93]:
# all rows, then a list of specific column labels to return
df.loc[:,['artist', 'album', 'claim_sales']].head()

            artist                                  album  claim_sales
year
1967   The Beatles  Sgt. Pepper's Lonely Hearts Club Band           32
1969   The Beatles                             Abbey Road           30
1971  Led Zeppelin                        Led Zeppelin IV           37
1973    Pink Floyd              The Dark Side of the Moon           45
1973    Elton John              Goodbye Yellow Brick Road           30

In [94]:
# list of specific index values, then a list of specific column labels
df.loc[[1973,1987,2011], ['artist', 'album', 'claim_sales']]

               artist                      album  claim_sales
year
1973       Pink Floyd  The Dark Side of the Moon           45
1973       Elton John  Goodbye Yellow Brick Road           30
1987    Guns N' Roses   Appetite for Destruction           30
1987  Various artists              Dirty Dancing           32
1987  Michael Jackson                        Bad           35
2011            Adele                         21           31

### Selecting Without Copying
When we use `.loc[]` to select a subset of rows or columns, the result is a new object that shows us a subset of the data. The key distinction to understand is the difference between **reading** a portion of the DataFrame (using `.loc[]` on the right side of an assignment) and **writing** to the DataFrame (using `.loc[]` on the left side of an assignment). Operations in subsequent sections will make this difference concrete.

In [95]:
# READING from the DataFrame (on the RIGHT side of the =)
# Here, .loc[] extracts a subset and stores it in a new variable.
# The original 'df' remains untouched.
subset_sales = df.loc[1973, ['artist', 'claim_sales']]

print("READ operation (subset_scores):")
print(subset_sales)
print("\nNotice the original df is unchanged:")
print(df.head())
print("-" * 30)

READ operation (subset_scores):
          artist  claim_sales
year
1973  Pink Floyd           45
1973  Elton John           30

Notice the original df is unchanged:
      decade        artist                                  album  \
year
1967    1960   The Beatles  Sgt. Pepper's Lonely Hearts Club Band
1969    1960   The Beatles                             Abbey Road
1971    1970  Led Zeppelin                        Led Zeppelin IV
1973    1970    Pink Floyd              The Dark Side of the Moon
1973    1970    Elton John              Goodbye Yellow Brick Road

                                  genre  cert_sales  claim_sales
year
1967                               Rock        18.2           32
1969                               Rock        14.4           30
1971  Hard rock, heavy metal, folk rock        29.0           37
1973                   Progressive rock        24.4           45
1973           rock, pop rock glam rock         8.5           30
------------------------------

In [96]:
# WRITING to the DataFrame (on the LEFT side of the =)
# Here, .loc[] tells Pandas exactly where in the original 'df'
# to place the new values.
df.loc[1987, 'claim_sales'] = 100  # Updating a single value

print("WRITE operation (original df updated):")
print(df.loc[1987, ['artist', 'claim_sales']])

WRITE operation (original df updated):
               artist  claim_sales
year
1987    Guns N' Roses          100
1987  Various artists          100
1987  Michael Jackson          100

### Selection by Position Using `.iloc`

As with Series, I want you to know that selection by position can be done. However, we're not going to do too much of it in class, so I'll show just two examples.

Note: unlike `.loc`, slicing with `.iloc` works just like it does in python lists and strings; the stop value is not included.

In [97]:
# single index and single column, both by location
df.iloc[25,1]

'Alanis Morissette'

In [98]:
# index slice (with negative indexing), column slice
df.iloc[-10:-5, 0:3]

      decade                             artist                album
year
1992    1990                               ABBA  Gold: Greatest Hits
1992    1990  Whitney Houston / Various artists        The Bodyguard
1995    1990                  Alanis Morissette   Jagged Little Pill
1996    1990                        Celine Dion     Falling into You
1997    1990                       Shania Twain         Come On Over

### Selection by Condition Using Booleans

As we did with Series, we can create and apply Boolean masks to select data.

In [99]:
# make a mask selecting rows where certified sales greater than 30 (million)
csales30_mask = df.loc[:,'cert_sales'] > 30

# select only those rows in the dataset where mask is true, and all columns
df.loc[csales30_mask,:]

,decade,artist,album,genre,cert_sales,claim_sales
year,,,,,,
1976,1970,Eagles,Hotel California,Soft rock,31.5,32
1976,1970,Eagles,Their Greatest Hits (1971–1975),"Country rock, soft rock, folk rock",41.2,42
1982,1980,Michael Jackson,Thriller,"Pop, post-disco, funk, rock",47.3,66

In [100]:
# make a mask selecting all rows where jackson is the artist
jackson_mask = df.loc[:, 'artist'] == 'Michael Jackson'

# select rows where the Jackson mask is True, and all columns
df.loc[jackson_mask, :]

,decade,artist,album,genre,cert_sales,claim_sales
year,,,,,,
1982,1980,Michael Jackson,Thriller,"Pop, post-disco, funk, rock",47.3,66
1987,1980,Michael Jackson,Bad,"Pop, rhythm and blues, funk and rock",22.2,100
1991,1990,Michael Jackson,Dangerous,"New jack swing, R&B and pop",17.0,32

Multiple masks can also be used simultaneously.

In [101]:
# select rows with Jackson and greater than 30 (million) certified sales, and all columns
df.loc[jackson_mask & csales30_mask, :]

,decade,artist,album,genre,cert_sales,claim_sales
year,,,,,,
1982,1980,Michael Jackson,Thriller,"Pop, post-disco, funk, rock",47.3,66

We are going to practice this sort of indexing a lot, so I'll provide more examples, and some more discussion, later.

With selection under our belt, let's move on to modifying the Dataframe — adding, removing, and updating rows and columns.

## Basic Operations

### Modifying Rows and Columns

### Creating a New Row

In [102]:
# creates a new row by setting values to an index label that does not exist
# note the omission of the comma and colon in the square brackets
if 2020 not in df.index:
    df.loc[2020] = [2020, 'Various', 'Baby Shark EDM Remix VII', 'Children', 80, 220]

# check the result
df.loc[2000:, :].head()

,decade,artist,album,genre,cert_sales,claim_sales
year,,,,,,
2000,2000,The Beatles,1,Rock,23.4,31
2011,2010,Adele,21,"Pop, soul",25.3,31
2020,2020,Various,Baby Shark EDM Remix VII,Children,80.0,220

### Creating a New Column

In [103]:
# creates a new column, by setting a value to a column label that does not exist
df.loc[:,'awesomeness'] = 5

# check the result
df.loc[:, ['artist', 'album', 'awesomeness']].head(3)

            artist                                  album  awesomeness
year
1967   The Beatles  Sgt. Pepper's Lonely Hearts Club Band            5
1969   The Beatles                             Abbey Road            5
1971  Led Zeppelin                        Led Zeppelin IV            5

### Copying a Series in a Dataframe

To copy a single series in a dataframe, you can assign the existing column values to a new column name.

In [104]:
# use a new label and assign it the values from the series to by copied
df.loc[:, 'album_duplicated'] = df.loc[:, 'album']

# check the result
df.loc[:, ['album', 'album_duplicated']].head(3)

,album,album_duplicated
year,,
1967,Sgt. Pepper's Lonely Hearts Club Band,Sgt. Pepper's Lonely Hearts Club Band
1969,Abbey Road,Abbey Road
1971,Led Zeppelin IV,Led Zeppelin IV

To copy multiple columns, we can specify the new column labels using a list, and specify the columns to be copied using another list. Unlike copying a single column, when we are copying multiple columns, we need to specify that we are copying the values of the columns. Without `.values`, Pandas tries to align the copied data by column name, since the new labels (`'certsales_duplicated'`, `'claimsales_duplicated'`) don't match the originals, it would fill everything with NaN.

In [105]:
# copying multiple series

# create list of new value names, just so the next bit of code isn't too lengthy
new_labels = ['certsales_duplicated', 'claimsales_duplicated']

# provide the new labels, assign values of columns to be copied, note the use of .values
df.loc[:, new_labels] = df.loc[:, ['cert_sales', 'claim_sales']].values

# check the result
df.loc[:, :].head(3)

,decade,artist,album,genre,cert_sales,claim_sales,awesomeness,album_duplicated,certsales_duplicated,claimsales_duplicated
year,,,,,,,,,,
1967,1960,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32,5,Sgt. Pepper's Lonely Hearts Club Band,18.2,32.0
1969,1960,The Beatles,Abbey Road,Rock,14.4,30,5,Abbey Road,14.4,30.0
1971,1970,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37,5,Led Zeppelin IV,29.0,37.0

### Deleting Rows and Columns
We can remove columns or rows from a Dataframe by using the Dataframe method `.drop()`. Drop takes the index or column labels you want to drop.

In [106]:
# dropping a column by column label
df = df.drop(columns = 'claimsales_duplicated')

# dropping multiple columns using a list of label
df = df.drop(columns = ['album_duplicated','certsales_duplicated'])

# check result
df.head(3)

,decade,artist,album,genre,cert_sales,claim_sales,awesomeness
year,,,,,,,
1967,1960,The Beatles,Sgt. Pepper's Lonely Hearts Club Band,Rock,18.2,32,5
1969,1960,The Beatles,Abbey Road,Rock,14.4,30,5
1971,1970,Led Zeppelin,Led Zeppelin IV,"Hard rock, heavy metal, folk rock",29.0,37,5

We can remove rows by specifying rows rather than columns.

In [107]:
df.tail(3)

,decade,artist,album,genre,cert_sales,claim_sales,awesomeness
year,,,,,,,
2000,2000,The Beatles,1,Rock,23.4,31,5
2011,2010,Adele,21,"Pop, soul",25.3,31,5
2020,2020,Various,Baby Shark EDM Remix VII,Children,80.0,220,5

In [108]:
# deleting a row using a row label
df = df.drop(index = 2020)

# check the result, no more baby shark
df.tail(3)

,decade,artist,album,genre,cert_sales,claim_sales,awesomeness
year,,,,,,,
1999,1990,Santana,Supernatural,Latin rock,20.5,30,5
2000,2000,The Beatles,1,Rock,23.4,31,5
2011,2010,Adele,21,"Pop, soul",25.3,31,5

### Updating Values
Like a list, a series is mutable, so values can be updated using indexing with `.loc` or `iloc`.

In [109]:
# select all rows, where the artist column is either Eagles or Celine Dion
not_awesome_mask = df.loc[:, 'artist'].isin(['Eagles', 'Celine Dion'])

# update a value based on a label
df.loc[not_awesome_mask, 'awesomeness'] = 1

#check the result
df.loc[[1976,1996,1997], ['artist', 'album', 'awesomeness']]

            artist                                   album  awesomeness
year
1976        Eagles                        Hotel California            1
1976        Eagles         Their Greatest Hits (1971–1975)            1
1996   Celine Dion                        Falling into You            1
1997  Shania Twain                            Come On Over            5
1997  James Horner  Titanic: Music from the Motion Picture            5
1997   Celine Dion                   Let's Talk About Love            1

It's entirely possible people bought the Titanic soundtrack just because of Celine Dion, so let's make one more alteration.

In [110]:
# create a mask to select the row with Titanic by album name
titanic_mask = df.loc[:, 'album'] == 'Titanic: Music from the Motion Picture'

# use the mask to select the row and set the value
df.loc[titanic_mask, 'awesomeness'] = 2

#check the result
df.loc[[1976,1996,1997], ['artist', 'album', 'awesomeness']]

            artist                                   album  awesomeness
year
1976        Eagles                        Hotel California            1
1976        Eagles         Their Greatest Hits (1971–1975)            1
1996   Celine Dion                        Falling into You            1
1997  Shania Twain                            Come On Over            5
1997  James Horner  Titanic: Music from the Motion Picture            2
1997   Celine Dion                   Let's Talk About Love            1

Note: setting or 'updating' variables with `.loc` or `.iloc`, as we have in this section, changes the DataFrame directly. We do not need to make a copy of the DataFrame to make the change.

### Basic Math Operations
If we have an entire dataframe of integers or floats, we can do math operations in the same way we do with series. If we've got a dataframe with mixed data-types, we need to specify the correct columns before we do the math.

In [111]:
# put sales column labels into a list
sales_columns = ['cert_sales', 'claim_sales']

# before the math operation
df.loc[:, sales_columns].head(3)

      cert_sales  claim_sales
year
1967        18.2           32
1969        14.4           30
1971        29.0           37

In [112]:
# update the sales_column, add five to all values
df.loc[:, sales_columns] = df.loc[:, sales_columns] + 5

# after the math operation
df.loc[:, sales_columns].head(3)

      cert_sales  claim_sales
year
1967        23.2           37
1969        19.4           35
1971        34.0           42

### Basic String Operations
The same applies to string operations. All the same string methods that were available with series can still be applied to a series in a Dataframe.

In [113]:
# before using the a string method
df.loc[:, 'genre'].head(3)

year
1967                                 Rock
1969                                 Rock
1971    Hard rock, heavy metal, folk rock
Name: genre, dtype: object

In [114]:
# creates a series with strings as values
df.loc[:, 'genre'] = df.loc[:, 'genre'].str.lower()
df.loc[:, 'genre'].head(3)

year
1967                                 rock
1969                                 rock
1971    hard rock, heavy metal, folk rock
Name: genre, dtype: object

### More Examples with a Different Dataset
I've grabbed some data on the estimated population of each U.S. State in 2019 [from this website](https://www.infoplease.com/us/states/state-population-by-rank) and information about grammy winners by state [from this website](https://www.decluttr.com/blog/2018/01/18/which-state-has-produced-the-most-big-four-grammy-winners/).

In [115]:
state_list = ['California', 'Texas', 'Florida', 'New York', 'Illinois',
              'Pennsylvania', 'Ohio', 'Georgia', 'North Carolina', 'Michigan',
              'New Jersey', 'Virginia', 'Washington', 'Arizona','Massachusetts',
              'Tennessee', 'Indiana', 'Missouri', 'Maryland', 'Wisconsin',
              'Colorado', 'Minnesota', 'South Carolina', 'Alabama', 'Louisiana',
              'Kentucky', 'Oregon', 'Oklahoma', 'Connecticut', 'Utah', 'Iowa',
              'Nevada', 'Arkansas', 'Mississippi', 'Kansas', 'New Mexico',
              'Nebraska', 'West Virginia', 'Idaho', 'Hawaii', 'New Hampshire',
              'Maine', 'Montana', 'Rhode Island', 'Delaware', 'South Dakota',
              'North Dakota', 'Alaska', 'DC', 'Vermont', 'Wyoming']

population_list = [39512223, 28995881, 21477737, 19453561, 12671821, 12801989,
                   11689100, 10617423, 10488084, 9986857, 8882190, 8535519,
                   7614893, 7278717, 6949503, 6833174, 6732219, 6137428,
                   6045680, 5822434, 5758736, 5639632, 5148714, 4903185,
                   4648794, 4467673, 4217737, 3956971, 3565287, 3205958,
                   3155070, 3080156, 3017825, 2976149, 2913314, 2096829,
                   1934408, 1792147, 1787065, 1415872, 1359711, 1344212,
                   1068778, 1059361, 973764, 884659, 762062, 731545, 705749,
                   623989, 578759]

# by state, alphabetical; DC has no data in the source and is stored as None
grammy_list = [3,0,0,3,27,1,1,None,0,2,10,3,0,15,3,1,1,1,1,2,3,4,4,3,2,5,0,1,
               0,0,15,0,49,3,0,8,2,1,7,1,1,1,7,12,0,0,3,3,0,1,0]

# zip() pairs corresponding elements from the two lists; pd.DataFrame converts those pairs
# into a two-column DataFrame — one row per state
dfg = pd.DataFrame(list(zip(state_list, population_list)),
                   columns=['state', 'population'])

# sort the Dataframe by state
dfg = dfg.sort_values('state')

# add the grammy count as a new column
dfg.loc[:,'grammies'] = grammy_list

# set the index to state
dfg = dfg.set_index('state')

# check the result
dfg.head()

            population  grammies
state
Alabama        4903185       3.0
Alaska          731545       0.0
Arizona        7278717       0.0
Arkansas       3017825       3.0
California    39512223      27.0

What are the top ten states for total number of grammy winners?

In [116]:
dfg.sort_values('grammies', ascending=False).head(10)

              population  grammies
state
New York        19453561      49.0
California      39512223      27.0
New Jersey       8882190      15.0
Illinois        12671821      15.0
Texas           28995881      12.0
Georgia         10617423      10.0
Ohio            11689100       8.0
Pennsylvania    12801989       7.0
Tennessee        6833174       7.0
Missouri         6137428       5.0

What are the five most populous states that have never won a grammy?

In [117]:
# create a no grammy mask that selects winless states
# fillna(0) treats states with missing Grammy data (DC) as zero
no_grammy_mask = (dfg.loc[:, 'grammies'].fillna(0) == 0)

# apply the mask to the rows, then sort by population
dfg.loc[no_grammy_mask, :].sort_values('population', ascending=False).head(5)

               population  grammies
state
Arizona           7278717       0.0
Utah              3205958       0.0
Nevada            3080156       0.0
New Mexico        2096829       0.0
West Virginia     1792147       0.0

What are the top ten states for winning grammies as a proportion of their population size?

In [118]:
# calculate winners per million
winners_per_mil = (dfg.loc[:, 'grammies'] / dfg.loc[:, 'population']) * 1000000

# sort and display result
winners_per_mil.sort_values(ascending=False).head(10)

state
New York        2.518819
Hawaii          2.118836
New Jersey      1.688773
Maine           1.487861
Illinois        1.183729
South Dakota    1.130379
Tennessee       1.024414
Arkansas        0.994093
Rhode Island    0.943965
Georgia         0.941848
dtype: float64

New York still tops the list when we account for the population size. Hawaii is not too far behind! Also, Maine? And California is no where to be seen.  Lots of surprises here.

---
**Note:** The next section loads the Titanic dataset and reassigns `df`. From this point forward, `df` refers to Titanic passenger data, not the album data used earlier in this notebook.

## Dataframes: Boolean Combinations and Negations

In [119]:
# loads the Titanic dataset — note: this reassigns df from the album data used earlier
url = 'https://raw.githubusercontent.com/bsheese/CSDS125ExampleData/master/data_titanic.csv'
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 887 non-null    int64
 1   Pclass                   887 non-null    int64
 2   Name                     887 non-null    object
 3   Sex                      887 non-null    object
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64
 6   Parents/Children Aboard  887 non-null    int64
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

### Combining Booleans  
We can take the basic idea of a boolean mask and extend it to a subset our dataframe in any way we like.

In [120]:
# a boolean mask
df.loc[:, 'Age'] > 45

0      False
1      False
2      False
3      False
4      False
       ...
882    False
883    False
884    False
885    False
886    False
Name: Age, Length: 887, dtype: bool

In [121]:
# using the mask to index the dataframe

# these two lines of code do the same thing...
over45_mask = df['Age'] > 45
df.loc[over45_mask, :].head()

# as this line of code, which is harder to read
df.loc[df['Age'] > 45, :].head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
31,1,1,Mrs. William Augustus (Marie Eugenie) Spencer,female,48.0,1,0,146.5208
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.5000

We can also combine as many booleans as we like.
For example, we can find any passenger that is both female and over 45 years of age by combining the two booleans. There is one complication, however. In Python, when we use `and` we are comparing the truth value of two statements, and returning 'True' if both are true.

In Pandas, we are comparing the truth value of many pairs of values in a series. Each comparison evaluates to True or False. To combine multiple booleans, we are going to use the `&` operator instead of Python's `and`.

Again, this is necessary because we are evaluating a series of boolean pairs, rather than just two singular objects. If you accidentally use `and` instead of `&` when combining boolean series in Pandas, you may get an error stating the 'truth value of a series is ambiguous'.

### Combining Booleans with &

In [122]:
# two booleans joined with an `&` creates a boolean series that we can use as a mask
# if either is False this evaluates to False
(df.loc[:, 'Age'] > 15) & (df.loc[:, 'Sex'] == 'female')

0      False
1       True
2       True
3       True
4      False
       ...
882    False
883     True
884    False
885    False
886    False
Length: 887, dtype: bool

In [123]:
# combine three booleans to find female passengers older than 45 who paid more than 100
df.loc[(df.loc[:, 'Age'] > 45) &
       (df.loc[:, 'Sex'] == 'female') &
       (df.loc[:, 'Fare'] > 100)].head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
31,1,1,Mrs. William Augustus (Marie Eugenie) Spencer,female,48.0,1,0,146.5208
194,1,1,Miss. Elise Lurette,female,58.0,0,0,146.5208
266,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58.0,0,1,153.4625
297,1,1,Mrs. James (Helene DeLaudeniere Chaput) Baxter,female,50.0,0,1,247.5208

### Combining Booleans with |
We must also use `|` instead of `or`, for the same reasons we couln't use `and`.

In [124]:
# using `|` to find passengers under 10 or over 60
df.loc[(df.loc[:, 'Age'] > 60) |
       (df.loc[:, 'Age'] < 10)].head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.075
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.700
16,0,3,Master. Eugene Rice,male,2.0,4,1,29.125
24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.075
33,0,2,Mr. Edward H Wheadon,male,66.0,0,0,10.500

### Simple Examples Using & and |

In [125]:
# create an empty dataframe
df_bool = pd.DataFrame(dtype=bool, index = range(0,4))

# create columns of True and False
df_bool.loc[:, 'T'] = True
df_bool.loc[:, 'F'] = False

# combine with bitwise and
df_bool.loc[:, 'T & F'] = (df_bool.loc[:, 'T'] & df_bool.loc[:, 'F'])

# combine with bitwise or
df_bool.loc[:, 'T | F'] = (df_bool.loc[:, 'T'] | df_bool.loc[:, 'F'])

# check the result
df_bool

      T      F  T & F  T | F
0  True  False  False   True
1  True  False  False   True
2  True  False  False   True
3  True  False  False   True

### Negating Booleans with ~
With standard Python we were able to negate booleans (turn True to False or False to True) by inserting `not` in front of the boolean.

In [126]:
not True

False

In [127]:
not False

True

We will sometimes want to do the same thing with a whole series of booleans. But we can't use `not` because it won't compare all of the values in the series. We have to use the bitwise version of `not` instead, with is the tilde character: `~`.

In [128]:
# create an empty dataframe
df_bool = pd.DataFrame(dtype=bool, index = range(0,4))

# create a column of True
df_bool.loc[:, 'T'] = True

# negate the True column
df_bool.loc[:, '~T'] = ~df_bool.loc[:, 'T']

# check the result
df_bool

      T     ~T
0  True  False
1  True  False
2  True  False
3  True  False

In [129]:
# create a column of False
df_bool.loc[:, 'F'] = False

# negate the False column
df_bool.loc[:, '~F'] = ~df_bool.loc[:, 'F']

# check the result
df_bool

      T     ~T      F    ~F
0  True  False  False  True
1  True  False  False  True
2  True  False  False  True
3  True  False  False  True

### Examples of Combinations and Negations
Below we use a pandas string method `str.startswith()` that returns a boolean value if the value in the series starts with the string specified as the argument. So pandas will look at the string we passed as the argument and compare it to each value in the series. If the value in the series starts with the string, pandas returns `True`. Otherwise, it returns `False`.

In [130]:
# a boolean series indicating passengers names that start with 'Mrs.'
df.loc[:, 'Name'].str.startswith('Mrs.')

0      False
1       True
2      False
3       True
4      False
       ...
882    False
883    False
884    False
885    False
886    False
Name: Name, Length: 887, dtype: bool

So we can use `str.startswith()` to create boolean masks to create dataframes with only a subset of the data. In this case, we are going to create different views into the dataframe:
* all passengers whose name starts with `'Mrs.'`
* all passengers whose name starts with `'Miss.'`.

In [131]:
# select all rows where the name starts with 'Mrs.' and assign to df_mrs
df_mrs = df.loc[df.loc[:, 'Name'].str.startswith('Mrs.')]

# select all rows where the name starts with 'Miss.' and assign to df_miss
df_miss = df.loc[df.loc[:,'Name'].str.startswith('Miss.')]

# use the two filtered DataFrames to get the mean age for each
print('Average age of Mrs. passengers:', df_mrs.loc[:, 'Age'].mean())
print('Average age of Miss. passengers:', df_miss.loc[:, 'Age'].mean())

Average age of Mrs. passengers: 35.768
Average age of Miss. passengers: 21.994505494505493

Look at the code below and see if you can figure out what it will do before you look at the result.

In [132]:
# note that these are all negated
mask_miss   = ~df.loc[:, 'Name'].str.contains('Miss')
mask_mrs    = ~df.loc[:, 'Name'].str.contains('Mrs.')
mask_mr     = ~df.loc[:, 'Name'].str.contains('Mr.')
mask_master = ~df.loc[:, 'Name'].str.contains('Master')

df.loc[mask_miss & mask_mrs & mask_mr & mask_master, :].tail(25)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
149,0,2,Rev. Robert James Bateman,male,51.0,0,0,12.5250
244,0,1,Dr. William Edward Minahan,male,44.0,2,0,90.0000
248,0,2,Rev. Ernest Courtenay Carter,male,54.0,1,0,26.0000
315,0,2,Dr. Ernest Moraweck,male,54.0,0,0,14.0000
367,1,1,Mme. Leontine Pauline Aubart,female,24.0,0,0,69.3000
396,0,2,Dr. Alfred Pain,male,23.0,0,0,10.5000
440,1,2,Ms. Encarnacion Reynaldo,female,28.0,0,0,13.0000
446,1,1,Major. Arthur Godfrey Peuchen,male,52.0,0,0,30.5000
533,0,1,Major. Archibald Willingham Butt,male,45.0,0,0,26.5500
553,1,1,Lady. (Lucille Christiana Sutherland)Duff Gordon,female,48.0,1,0,39.6000
596,1,1,Sir. Cosmo Edmund Duff Gordon,male,49.0,1,0,56.9292
623,0,2,Rev. Charles Leonard Kirkland,male,57.0,0,0,12.3500
629,1,1,Dr. Max Stahelin-Maeglin,male,32.0,0,0,30.5000
638,1,1,Mlle. Emma Sagesser,female,24.0,0,0,69.3000
644,1,1,Col. Oberst Alfons Simonius-Blumer,male,56.0,0,0,35.5000
657,1,1,Dr. Henry William Frauenthal,male,50.0,2,0,133.6500
691,0,1,Col. John Weir,male,60.0,0,0,26.5500
707,1,1,Mlle. Berthe Antonine Mayne,female,24.0,0,0,49.5042
741,0,1,Capt. Edward Gifford Crosby,male,70.0,1,1,71.0000
755,1,1,the Countess. of (Lucy Noel Martha Dyer-Edward...,female,33.0,0,0,86.5000
762,0,1,Dr. Arthur Jackson Brewe,male,46.0,0,0,39.6000
792,1,1,Dr. Alice (Farnham) Leader,female,49.0,0,0,25.9292
818,0,1,Jonkheer. John George Reuchlin,male,38.0,0,0,0.0000
844,0,2,Rev. John Harper,male,28.0,0,1,33.0000
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000

Random observations:
* None of the Reverends survived.
* Dr. Pain died at 23.
* Major Archibald Butt had quite a career, and there are some interesting, but unverified, accounts of [his time on the titanic](https://en.wikipedia.org/wiki/Archibald_Butt).
*  In case you're [wondering what a Jonkheer denotes](https://en.wikipedia.org/wiki/Jonkheer).

Another pandas string method that comes in handy is `str.contains()`. It will return True for any series value that contains the string that is passed as an argument. We can use this to find the Palsson family. A sad story in four rows of a dataframe.

In [133]:
df.loc[df.loc[:, 'Name'].str.contains('Palsson')]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.075
24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.075
372,0,3,Miss. Stina Viola Palsson,female,3.0,3,1,21.075
564,0,3,Mrs. Nils (Alma Cornelia Berglund) Palsson,female,29.0,0,4,21.075

The Sage family had a similarly sad fate.

In [134]:
df.loc[df.loc[:, 'Name'].str.contains('Sage')]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
158,0,3,Master. Thomas Henry Sage,male,5.0,8,2,69.55
179,0,3,Miss. Constance Gladys Sage,female,8.0,8,2,69.55
200,0,3,Mr. Frederick Sage,male,17.0,8,2,69.55
322,0,3,Mr. George John Jr Sage,male,20.0,8,2,69.55
638,1,1,Mlle. Emma Sagesser,female,24.0,0,0,69.30
788,0,3,Miss. Stella Anna Sage,female,21.0,8,2,69.55
842,0,3,Mr. Douglas Bullen Sage,male,18.0,8,2,69.55
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.55


Notice that passing 'Sage' as an argument has also returned the name 'Sagesser' above. To remove this entry we can combine booleans and the `~` character to return rows that contain Sage but do not contain 'Sagesser'.

In [135]:
df.loc[df.loc[:, 'Name'].str.contains('Sage') &
       ~df.loc[:, 'Name'].str.contains('Sagesser')]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
158,0,3,Master. Thomas Henry Sage,male,5.0,8,2,69.55
179,0,3,Miss. Constance Gladys Sage,female,8.0,8,2,69.55
200,0,3,Mr. Frederick Sage,male,17.0,8,2,69.55
322,0,3,Mr. George John Jr Sage,male,20.0,8,2,69.55
788,0,3,Miss. Stella Anna Sage,female,21.0,8,2,69.55
842,0,3,Mr. Douglas Bullen Sage,male,18.0,8,2,69.55
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.55

## Your Turn

At this point in the notebook, `df` contains the **Titanic** dataset.

1. Using the Titanic data (`df`), select all female passengers over 30 who survived. Combine two boolean masks with `&`. Print the number of matching rows using `len()`.

2. Using the Titanic data, compute the survival rate (proportion who survived) separately for male and female passengers. Use a boolean mask to select each gender, then call `.mean()` on the `Survived` column for each subset.

3. **Challenge:** Using the Titanic data, add a new column called `age_group` with the value `'child'` for passengers under 18 and `'adult'` for everyone else. Use two boolean masks and two `.loc[]` assignments. Display the first 10 rows showing only `Name`, `Age`, and `age_group`.

Check your answers by displaying the result for each exercise.

In [ ]:
# enter your responses here

---
That wraps up our introductory material. We've talked a bit about machine learning, and we've introduced the basic tool set. Next we will consider Simple Linear Regression (SLR).